---
- name: Configure Ceph Host(s)
  become: true
  hosts: ceph
  tasks:
    - name: Install Lvm2
      dnf:
        name: lvm2
        state: present
    - name: Install Python3
      dnf:
        name: python3
        state: present
    - name: Install Podman
      dnf:
        name: podman
        state: present
    - name: Disable Firewalld
      systemd:
        name: firewalld
        state: stopped

