---
- name: Configure Ceph Host(s)
  become: true
  hosts: ceph
  vars:
    docker_edition: 'ce'
    docker_service_state: started
    docker_service_enabled: true
    docker_install_compose: no
    docker_users:
      - centos
  roles:
    - geerlingguy.docker